lab_6/urls.py
from django.urls import path
from . import views
# url for app
app_name = 'lab_6'
urlpatterns = [
    path('', views.index, name='index'),
    path('delete/', views.delete_all, name='delete'),
    path('profile/', views.profile, name='profile')
]

ppw_lab6/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("lab_6.urls")),
    path('book/', include("lab_9.urls")),
    path('book/auth/', include('social_django.urls', namespace='social')),
    path('subscribe/', include("lab_10.urls")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_10/models.py
from django.db import models

# Create your models here.


class Subscriber(models.Model):
    email = models.EmailField(max_length=32, unique=True)
    name = models.CharField(max_length=32)
    password = models.CharField(max_length=32)

    def __str__(self):
        return self.email

lab_6/models.py
from django.db import models
from datetime import datetime
# Create your models here.


class Status(models.Model):
    status = models.CharField(max_length=300)
    date = models.DateTimeField(auto_now_add=True, null=True)

    # def __str__(self):
    #     return self.date

lab_6/forms.py
from django import forms
from .models import Status


class Status_Form(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['status']
        widgets = {
            'status': forms.Textarea(attrs={'class': 'form-control'})
        }

    def __init__(self, *args, **kwargs):
        super(Status_Form, self).__init__(*args, **kwargs)
        self.fields['status'].label = "Apa yang sedang kamu pikirkan?"

lab_6/views.py
from django.shortcuts import render, redirect
from .forms import Status_Form
from .models import Status

# Create your views here.


def index(request):
    if request.method == 'POST':
        form = Status_Form(request.POST)
        statuses = Status.objects.all().order_by('date')
        if form.is_valid():
            status = Status()
            status.status = form.cleaned_data['status']
            status.save()
            return redirect('lab_6:index')

    else:
        form = Status_Form()
        statuses = Status.objects.all().order_by('date')
    return render(request, 'index.html', {'form': form, 'statuses': statuses})


def delete_all(request):
    Status.objects.all().delete()
    return redirect('lab_6:index')


def profile(request):
    return render(request, 'profile.html')

lab_6/templates/index.html
{% extends "base.html" %}
{% load static %}
<!doctype html>
<html lang="en">

    {% block content %}
        <div class="container">
            <h1 class="text-center text-white" id="id_title">Hello, apa kabar?</h1>
            <div class="row">
                <div class="col-sm-6">
                    <form class="form-group" action="{% url 'lab_6:index' %}" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" class="btn btn-primary" value="Post" id="id_submit">
                    </form>
                    <a href="{% url 'lab_6:delete' %}" class="btn btn-danger" id="id_delete">Delete All</a>
                </div>
                <div class="col-sm-6">
                    <br>
                    {% for status in statuses %}
                        <div class="status rounded">
                            <h5>{{ status.date }}</h3>
                            <p>{{ status.status }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endblock %}

</body>
</html>

lab_6/templates/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <h3 class="btn btn-dark position-absolute" id="id_change">Change Style</h3>
    <div class="container text-center">
        <div class="text-center">
            <img src="{% static "image/ray.jpg" %}" class="rounded-circle" id="resize-img">
            <h1 class="font-weight-bold" id="id_name">Ray Azrin Karim</h1>
            <h5>1706044111</h5>
        </div>
        <div id="accordion">
            <h3 class="btn-primary rounded">Aktivitas</h3>
            <div class="bg-white rounded ">
                <p>
                    Aktivitas saya sekarang adalah kuliah, berkumpul dengan teman, rapat organisasi, serta rapat kepanitiaan.
                </p>
            </div>
            <h3 class="btn-primary rounded">Pengalaman Organisasi/Kepanitiaan</h3>
            <div class="bg-white rounded ">
                <ul>
                    <li>Staff BEM Fasilkom UI 2018 Departemen Akademis dan Kepemimpinan</li>
                    <li>Staff FUKI Fasilkom UI 2018 Departemen Muslim Development Center</li>
                    <li>Staff Bizzit Compfest X</li>
                    <li>Mentor OKK UI 2018</li>
                    <li>Staff Penunjang PMB 2018</li>

                </ul>
            </div>
            <h3 class="btn-primary rounded">Prestasi</h3>
            <div class="bg-white rounded ">
                <p>
                    Masuk UI
                </p>
            </div>
        </div>
    </div>
{% endblock %}

</html>