lab_6/urls.py
from django.urls import path
from . import views
# url for app
app_name = 'lab_6'
urlpatterns = [
    path('', views.index, name='index'),
    path('delete/', views.delete_all, name='delete'),
    path('profile/', views.profile, name='profile')
]

lab_9/urls.py
from django.urls import path

from . import views
app_name = 'lab_9'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('private/api/<str:search>', views.getJSON, name='books'),
    path('private/api/session/like/', views.like, name='like'),
    path('private/api/session/like/get/', views.get_like, name='get_like'),
    path('private/api/session/unlike/', views.unlike, name='unlike'),
]

ppw_lab6/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("lab_6.urls")),
    path('book/', include("lab_9.urls")),
    path('book/auth/', include('social_django.urls', namespace='social')),
    path('subscribe/', include("lab_10.urls")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_9/models.py
from django.db import models

# Create your models here.

lab_9/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_exempt
import requests

# Create your views here.

response = {}


def index(request):
    if request.user.is_authenticated and "like" not in request.session:
        request.session["fullname"] = request.user.first_name + \
            " " + request.user.last_name
        request.session["username"] = request.user.username
        request.session["email"] = request.user.email
        request.session["sessionid"] = request.session.session_key
        request.session["like"] = []
        for key, value in request.session.items():
            print('{} => {}'.format(key, value))
    return render(request, 'book.html')


def login(request):
    return render(request, 'login.html')


def logout_view(request):
    logout(request)
    return redirect('lab_9:index')


def getJSON(request, search='quilting'):
    json_data = requests.get(
        'https://www.googleapis.com/books/v1/volumes?q=' + search).json()
    arr_json = []
    for info in json_data['items']:
        data = {}
        data['title'] = info['volumeInfo']['title']
        if 'imageLinks' in info['volumeInfo']:
            data['thumbnail'] = info['volumeInfo']['imageLinks']['thumbnail']
        else:
            data['thumbnail'] = 'https://png.icons8.com/dotty/2x/nothing-found.png'
        if 'authors' in info['volumeInfo']:
            data['author'] = ", ".join(info['volumeInfo']['authors'])
        else:
            data['author'] = "Data tidak ditemukan"
        if 'publishedDate' in info['volumeInfo']:
            data['publishedDate'] = info['volumeInfo']['publishedDate']
        else:
            data['publishedDate'] = "Data tidak ditemukan"
        data['id'] = info['id']
        arr_json.append(data)

    response = {'data': arr_json}
    return JsonResponse(response)


@csrf_exempt
def like(request):
    if(request.method == "POST"):
        lst = request.session["like"]
        if request.POST["id"] not in lst:
            lst.append(request.POST["id"])
        request.session["like"] = lst
        response["message"] = len(lst)
        return JsonResponse(response)
    else:
        return HttpResponse("GET Method not allowed")


@csrf_exempt
def unlike(request):
    if(request.method == "POST"):
        lst = request.session["like"]
        if request.POST["id"] in lst:
            lst.remove(request.POST["id"])
        print(request.session["sessionid"])
        print(request.session["like"])
        request.session["like"] = lst
        response["message"] = len(lst)
        return JsonResponse(response)
    else:
        return HttpResponse("GET Method not allowed")


def get_like(request):
    if request.user.is_authenticated:
        if(request.method == "GET"):
            if request.session["like"] is not None:
                response["message"] = request.session["like"]
        else:
            response["message"] = "NOT ALLOWED"
    else:
        response["message"] = ""
    return JsonResponse(response)

lab_9/templates/book.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Books
{% endblock %}
{% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/book.css' %}">
    <script type="text/javascript" src="{% static "js/script.js" %}"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
{% endblock %}
{% block content %}
    <div class="container">
        {% if user.is_authenticated %}
            <p class="display-4">Hello,
                {{ user.first_name }}
                {{ user.last_name}}</p>
            <a class="btn btn-danger" href="{% url 'lab_9:logout' %}">Logout</a>

        {% else %}
            <h1>Haven't login yet?</h1>
            <a class="btn btn-primary" href="{% url 'social:begin' 'google-oauth2' %}">Login with google account</a>
        {% endif %}
        <div class="card-body row no-gutters align-items-center">
            <div class="col-auto">
                <i class="fas fa-search h4 text-body"></i>
            </div>
            <!--end of col-->
            <div class="col">
                <input class="form-control form-control-lg form-control-borderless" name="keyword" type="search" placeholder="Search topics or keywords">
            </div>
            <!--end of col-->
            <div class="col-auto">
                <button class="btn btn-lg btn-success" type="submit" onclick="search()">Search</button>
            </div>
            <!--end of col-->
        </div>
        <h1 id="favH1">Favorites :
            <i class="fas fa-sun"></i>
            <span class="counter">0</span></h1>
        <table class="table table-hover">
            <thead>
                <tr>
                    <td>No.</td>
                    <td>Cover</td>
                    <td>Title</td>
                    <td>Author</td>
                    <td>Published Date</td>
                    <td>Add to Favorites</td>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
{% endblock %}