lab_10/urls.py
from django.urls import path
from . import views
app_name = 'lab_10'

urlpatterns = [
    path('', views.index, name='index'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('validate_email/', views.validate, name='validate')
]

lab_6/urls.py
from django.urls import path
from . import views
# url for app
app_name = 'lab_6'
urlpatterns = [
    path('', views.index, name='index'),
    path('delete/', views.delete_all, name='delete'),
    path('profile/', views.profile, name='profile')
]

lab_9/urls.py
from django.urls import path

from . import views
app_name = 'lab_9'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('private/api/<str:search>', views.getJSON, name='books'),
    path('private/api/session/like/', views.like, name='like'),
    path('private/api/session/like/get/', views.get_like, name='get_like'),
    path('private/api/session/unlike/', views.unlike, name='unlike'),
]

ppw_lab6/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("lab_6.urls")),
    path('book/', include("lab_9.urls")),
    path('book/auth/', include('social_django.urls', namespace='social')),
    path('subscribe/', include("lab_10.urls")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>
            {%block title %}
                Document
            {% endblock %}
        </title>
        <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
        <link rel="stylesheet" href="{% static "css/style.css" %}">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src="{% static "js/lab6.js" %}"></script>
        {% block extrahead %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'lab_6:index' %}">LAB PPW</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab_6:index' %}">Status</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab_6:profile' %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab_9:index' %}">Books</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab_10:index' %}">Subscribe</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
        <h1></h1>
        {% block content %}{% endblock %}
    </body>
    <div class="se-pre-con"></div>
</html>